users:
  - name: bs
    uid: 2000

write_files:
  - path: /home/bs/tor_v3/hidden_service_v3/hs_ed25519_public_key.enc.b64
    permissions: 0600
    owner: root
    content: |
        ${v3_pubk}

  - path: /home/bs/tor_v3/hidden_service_v3/hs_ed25519_secret_key.enc.b64
    permissions: 0600
    owner: root
    content: |
        ${v3_pk}

  - path: /home/bs/tor_v2/hidden_service/private_key.enc.b64
    permissions: 0600
    owner: root
    content: |
        ${v2_pk}

  - path: /home/bs/torrcv2
    permissions: 0644
    owner: root
    content: |
        DataDirectory /home/tor/tor
        PidFile /var/run/tor/tor.pid

        ControlSocket /var/run/tor/control GroupWritable RelaxDirModeCheck
        ControlSocketsGroupWritable 1

        CookieAuthentication 1
        CookieAuthFileGroupReadable 1
        CookieAuthFile /var/run/tor/control.authcookie

        Log [*]notice stderr
        SOCKSPort 0

        HiddenServiceNonAnonymousMode 1
        HiddenServiceSingleHopMode 1
        HiddenServiceDir /home/tor/tor/hidden_service/
        HiddenServiceVersion  2
        HiddenServicePort 80 ${tor_lb}:80

  - path: /home/bs/torrcv3
    permissions: 0644
    owner: root
    content: |
        DataDirectory /home/tor/tor
        PidFile /var/run/tor/tor.pid

        ControlSocket /var/run/tor/control GroupWritable RelaxDirModeCheck
        ControlSocketsGroupWritable 1

        CookieAuthentication 1
        CookieAuthFileGroupReadable 1
        CookieAuthFile /var/run/tor/control.authcookie

        Log [*]notice stderr
        SOCKSPort 0

        HiddenServiceNonAnonymousMode 1
        HiddenServiceSingleHopMode 1
        HiddenServiceDir /home/tor/tor/hidden_service_v3/
        HiddenServiceVersion 3
        HiddenServicePort 80 ${tor_lb}:80

  - path: /home/bs/tor_v2/hidden_service/hostname
    permissions: 0600
    owner: root
    content: |
        ${v2_host}

  - path: /home/bs/tor_v2/hidden_service/onion_service_non_anonymous
    permissions: 0600
    owner: root
    content: |
        # this file is necessary for the non-anonymous service

  - path: /home/bs/tor_v3/hidden_service_v3/hostname
    permissions: 0600
    owner: root
    content: |
        ${v3_host}

  - path: /etc/systemd/system/decrypt.service
    permissions: 0644
    owner: root
    content: |
        [Unit]
        Description=decrypt secrets against KMS
        Wants=gcr-online.target
        After=gcr-online.target

        [Service]
        Type=oneshot
        RemainAfterExit=true
        Environment=HOME=/home/bs
        ExecStartPre=/usr/bin/docker-credential-gcr configure-docker
        ExecStartPre=/usr/bin/docker pull ${docker_tag_gcloud}
        ExecStart=/usr/bin/docker run \
            --name=decrypt \
            --rm \
            -v /home/bs/tor_v3/hidden_service_v3/:/root/secrets:rw \
            "${docker_tag_gcloud}" gcloud kms decrypt \
                --location=${kms_location} \
                --keyring=${kms_key_ring} \
                --key=${kms_key} \
                --ciphertext-file=/root/secrets/hs_ed25519_public_key.enc \
                --plaintext-file=/root/secrets/hs_ed25519_public_key
        ExecStart=/usr/bin/docker run \
            --name=decrypt \
            --rm \
            -v /home/bs/tor_v3/hidden_service_v3/:/root/secrets:rw \
            "${docker_tag_gcloud}" gcloud kms decrypt \
                --location=${kms_location} \
                --keyring=${kms_key_ring} \
                --key=${kms_key} \
                --ciphertext-file=/root/secrets/hs_ed25519_secret_key.enc \
                --plaintext-file=/root/secrets/hs_ed25519_secret_key
        ExecStart=/usr/bin/docker run \
            --name=decrypt \
            --rm \
            -v /home/bs/tor_v2/hidden_service/:/root/secrets:rw \
            "${docker_tag_gcloud}" gcloud kms decrypt \
                --location=${kms_location} \
                --keyring=${kms_key_ring} \
                --key=${kms_key} \
                --ciphertext-file=/root/secrets/private_key.enc \
                --plaintext-file=/root/secrets/private_key
        ExecStartPost=-/bin/rm /home/bs/tor_v3/hidden_service_v3/hs_ed25519_public_key.enc /home/bs/tor_v3/hidden_service_v3/hs_ed25519_public_key.enc.b64
        ExecStartPost=-/bin/rm /home/bs/tor_v3/hidden_service_v3/hs_ed25519_secret_key.enc /home/bs/tor_v3/hidden_service_v3/hs_ed25519_secret_key.enc.b64
        ExecStartPost=-/bin/rm /home/bs/tor_v2/hidden_service/private_key.enc /home/bs/tor_v2/hidden_service/private_key.enc.b64

  - path: /etc/systemd/system/torv2.service
    permissions: 0644
    owner: root
    content: |
        [Unit]
        Description=Tor V2 node
        Wants=gcr-online.target docker.service decrypt.service
        After=gcr-online.service docker.service decrypt.service

        [Service]
        Restart=always
        RestartSec=1
        Environment=HOME=/home/bs
        ExecStartPre=/usr/bin/docker-credential-gcr configure-docker
        ExecStartPre=/usr/bin/docker pull ${docker_tag}
        ExecStartPre=-/bin/chown -R bs:bs /home/bs/tor_v2/
        ExecStartPre=-/bin/chmod -R 2700 /home/bs/tor_v2/
        ExecStartPre=-/bin/chmod 0600 /home/bs/tor_v2/hidden_service/private_key
        ExecStart=/usr/bin/docker run \
            --log-driver=gcplogs \
            --network=host \
            --pid=host \
            --name=torv2 \
            --tmpfs /tmp/ \
            -v /home/bs/torrcv2:/home/tor/torrc:ro \
            -v /home/bs/tor_v2:/home/tor/tor:rw \
            "${docker_tag}" tor -f /home/tor/torrc
        ExecStop=/usr/bin/docker rm -f torv2

        [Install]
        WantedBy=multi-user.target

  - path: /etc/systemd/system/torv3.service
    permissions: 0644
    owner: root
    content: |
        [Unit]
        Description=Tor V3 node
        Wants=gcr-online.target docker.service decrypt.service
        After=gcr-online.service docker.service decrypt.service

        [Service]
        Restart=always
        RestartSec=1
        Environment=HOME=/home/bs
        ExecStartPre=/usr/bin/docker-credential-gcr configure-docker
        ExecStartPre=/usr/bin/docker pull ${docker_tag}
        ExecStartPre=-/bin/chown -R bs:bs /home/bs/tor_v3/
        ExecStartPre=-/bin/chmod -R 2700 /home/bs/tor_v3/
        ExecStartPre=-/bin/chmod 0644 /home/bs/tor_v3/hidden_service_v3/hs_ed25519_public_key
        ExecStartPre=-/bin/chmod 0600 /home/bs/tor_v3/hidden_service_v3/hs_ed25519_secret_key
        ExecStart=/usr/bin/docker run \
            --log-driver=gcplogs \
            --network=host \
            --pid=host \
            --name=torv3 \
            --tmpfs /tmp/ \
            -v /home/bs/torrcv3:/home/tor/torrc:ro \
            -v /home/bs/tor_v3:/home/tor/tor:rw \
            "${docker_tag}" tor -f /home/tor/torrc
        ExecStop=/usr/bin/docker rm -f torv3

        [Install]
        WantedBy=multi-user.target

  - path: /etc/systemd/system/node-exporter.service
    permissions: 0644
    owner: root
    content: |
        [Unit]
        Description=prometheus node-exporter
        Wants=gcr-online.target docker.service
        After=gcr-online.service docker.service

        [Service]
        Restart=always
        RestartSec=1
        Environment=HOME=/home/exec
        ExecStartPre=/usr/bin/docker-credential-gcr configure-docker
        ExecStartPre=/usr/bin/docker pull ${docker_tag_node_exporter}
        ExecStartPre=/sbin/iptables -A INPUT -m tcp -p tcp --dport 9100 -j ACCEPT
        ExecStart=/usr/bin/docker run \
            --log-driver=gcplogs \
            --name=node-exporter \
            --network=host \
            --read-only \
            -v /proc:/host/proc:ro \
            -v /sys:/host/sys:ro \
            -v /:/rootfs:ro \
            -v metrics:/metrics:ro \
            -v /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket:ro \
            "${docker_tag_node_exporter}" --path.procfs /host/proc --path.sysfs /host/sys --collector.textfile.directory /metrics --collector.filesystem.ignored-mount-points "^/(sys|proc|dev|host|etc($|/))" --collector.systemd
        ExecStop=/usr/bin/docker stop node-exporter
        ExecStopPost=/usr/bin/docker rm node-exporter
        ExecStopPost=/sbin/iptables -D INPUT -m tcp -p tcp --dport 9100 -j ACCEPT

        [Install]
        WantedBy=multi-user.target

runcmd:
  - systemctl daemon-reload
  - base64 -d /home/bs/tor_v3/hidden_service_v3/hs_ed25519_public_key.enc.b64 > /home/bs/tor_v3/hidden_service_v3/hs_ed25519_public_key.enc
  - base64 -d /home/bs/tor_v3/hidden_service_v3/hs_ed25519_secret_key.enc.b64 > /home/bs/tor_v3/hidden_service_v3/hs_ed25519_secret_key.enc
  - base64 -d /home/bs/tor_v2/hidden_service/private_key.enc.b64 > /home/bs/tor_v2/hidden_service/private_key.enc
  - systemctl enable torv2.service
  - systemctl enable torv3.service
  - systemctl enable decrypt.service
  - systemctl start decrypt.service
  - systemctl start torv2.service
  - systemctl start torv3.service
  - systemctl enable node-exporter.service
  - systemctl start node-exporter.service
